spring.application.name=speech
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:sqlite:/data/app.db?foreign_keys=on}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
server.port=${PORT:8080}